# Generated by Django 5.2.4 on 2025-07-21 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('year_of_graduation', models.PositiveIntegerField()),
                ('certificate_number', models.CharField(max_length=50, unique=True)),
                ('course_of_study', models.CharField(max_length=255)),
                ('certificate_file', models.FileField(upload_to='certificates/')),
            ],
        ),
    ]
